### ISSUE TITLE
As an Admin I can create community(new)

### ISSUE THREAD

**Issue by mariam-ismail** [yousraHazem/topsoft-13#114]
c2_mariam_create_edit_communtiy_last
Success:
the "create community" button only appears to the admin --> he will add required fields community name, description(optional),groups(optional),creators when you press submit it redirect to the community page

Failure:
admin leaves required fields empty or the community already exists on the DB

Tasks:
1. Research on validations
2. Documentation
4. Implementing the function logic
5. Handling input errors
6. CSS & Bootstrap

**Comment by mayBadr** [comment]
ok

**Comment by mariam-ismail** [comment]
@Donia1 @samaakram @sarahahmed @mayBadr

**Comment by mariam-ismail** [comment]
@Donia1 please check my UMLS

**Comment by mariam-ismail** [comment]
@sarahahmed please check my tests

**Comment by mariam-ismail** [comment]
@samaakram  please review my documentation and code

**Comment by Donia1** [comment]
mariam let the arrows be inside the opt box not outside

**Comment by sarahahmed** [comment]
tests are correct

**Comment by mariam-ismail** [comment]
@Donia1 please recheck my UMLS

**Comment by mariam-ismail** [comment]
@samaakram please check my code and documentation

**Comment by Donia1** [comment]
checked your uml verified

**Comment by mariam-ismail** [comment]
@samaakram  could you please check my code and documentaion

**Comment by samaakram** [comment]
@mariam-ismail 
doc review:
in CommunitiesController:
for each method you have to specify its ARGS and what it returns

**Comment by samaakram** [comment]
@mariam-ismail:
code review:
 views / communities / admin.html.erb &  views / communities / list.html.erb &  views / communities / show.html.erb & CommunitiesController

fix the indentation

in  views / communities / edit.html.erb:
fix indentation and one ending p ( </p> ) is missing

**Comment by mariam-ismail** [comment]
@Donia1  please recheck my UMLS

**Comment by mariam-ismail** [comment]
@Riham-Gamal  please review my scenario

**Comment by mariam-ismail** [comment]
@samaakram please review my code and documentation

**Comment by Riham-Gamal** [comment]
@mariam-ismail i reviewd the scenaio but there is a uniquness validation on the email why???

**Comment by mariam-ismail** [comment]
@Riham-Gamal  I removed the validation please recheck

**Comment by mariam-ismail** [comment]
@sarahahmed please re-verify my tests

**Comment by Donia1** [comment]
verified

**Comment by sarahahmed** [comment]
tests are correct

**Comment by samaakram** [comment]
@mariam-ismail 
code review:
CommunitiesController line 25: indentation problem
line 7 is empty this drives git crazy :d remove it
and the view also fix the indentation please :)

**Comment by mariam-ismail** [comment]
@samaakram fixed the problem please recheck

**Comment by samaakram** [comment]
@mariam-ismail code verified

**Comment by Riham-Gamal** [comment]
scenariio verified

**Comment by samaakram** [comment]
@mariam-ismail 
doc verified
