### ISSUE TITLE
As an Admin I can edit a community(new)

### ISSUE THREAD

**Issue by mariam-ismail** [yousraHazem/topsoft-13#115]
c2_mariam_create_edit_communtiy_last
Success:
he edited  his work only, redirect it to the same page after editing, after you finish editing you get an alert are you sure of your changes

Failure:
edited something that he didn't create, deleted a required field

Tasks:
1. Research on validations
2. Documentation
4. Implementing the function logic
5. Handling input errors
6. CSS & Bootstrap

**Comment by mariam-ismail** [comment]
@Donia1 @mayBadr @samaakram @sarahahmed

**Comment by mayBadr** [comment]
ok

**Comment by mariam-ismail** [comment]
@sarahahmed please check my tests

**Comment by mariam-ismail** [comment]
@samaakram  please review my code and documentation

**Comment by sarahahmed** [comment]
tests are correct

**Comment by mariam-ismail** [comment]
@Donia1 please recheck my UMLS

**Comment by Donia1** [comment]
checked your uml verified

**Comment by mariam-ismail** [comment]
@samaakram  could you please check my code and documentaion

**Comment by mariam-ismail** [comment]
@samaakram  could you please check my code and documentaion

**Comment by samaakram** [comment]
@mariam-ismail:
code review:
views / communities / admin.html.erb & views / communities / list.html.erb & views / communities / show.html.erb & CommunitiesController

fix the indentation

in views / communities / edit.html.erb:
fix indentation and one ending p (
) is missing

**Comment by samaakram** [comment]
@mariam-ismail 
doc review:
in CommunitiesController:
for each method you have to specify its ARGS and what it returns

**Comment by mariam-ismail** [comment]
@Donia1  please recheck my UMLS

**Comment by mariam-ismail** [comment]
@Riham-Gamal  please review my scenario

**Comment by mariam-ismail** [comment]
@samaakram please review my code and documentation

**Comment by mariam-ismail** [comment]
@Riham-Gamal  I removed the validation please recheck

**Comment by mariam-ismail** [comment]
@sarahahmed please re-verify the tests

**Comment by Donia1** [comment]
@mariam-ismail verified

**Comment by samaakram** [comment]
@mariam-ismail 
Code review
CommunitiesController line 42 and 44: indentation problems
and the view also fix the indentation please :)

**Comment by mariam-ismail** [comment]
@samaakram fixed the problem please recheck

**Comment by samaakram** [comment]
@mariam-ismail code verified

**Comment by Riham-Gamal** [comment]
scenario verified

**Comment by samaakram** [comment]
@mariam-ismail 
doc verified
