### ISSUE TITLE
As a Guest i can view the operational budget items

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#140]
Success 
When a guest wants to view the budget only the operational budget items appear to them 

@yasmin-eltahan  @sarahahmed @Riham-Gamal @salmaelruby

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan please review my senario
@sarahahmed  please review my tests
@Riham-Gamal please review my code
@salmaelruby please review my documentation

**Comment by tokaabdelgabar** [comment]
@sarahahmed please review my tests (they run)
@yasmin-eltahan the senario
@Riham-Gamal please review my code
@salmaelruby please review my documentation

**Comment by sarahahmed** [comment]
tests are correct

**Comment by yasmin-eltahan** [comment]
please remove twitter bootstrap

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan I removed twitter bootstrap

**Comment by yasmin-eltahan** [comment]
@please add bootstrap gem the gem file

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  please check the senario and uml

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  for the scenario it only applies if the project id is 1 

for the uml same comment as before

**Comment by tokaabdelgabar** [comment]
@salmaelruby  please verify the documentation

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  can you check the senario

**Comment by salmaelruby** [comment]
doc verified

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  please fix the bootstrap issue

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  UML verified
