### ISSUE TITLE
As a project admin, i can create and edit budget item components

### ISSUE THREAD

**Issue by sarahahmed** [yousraHazem/topsoft-13#141]
@yasmin-eltahan 
@tokaabdelgabar 
@nayera-muhammad

**Comment by yasmin-eltahan** [comment]
I verified UML

**Comment by yasmin-eltahan** [comment]
I verified senario

**Comment by sarahahmed** [comment]
@nayera-muhammad i updated the tests, please review me

**Comment by nayera-muhammad** [comment]
and mention the branch name

**Comment by nayera-muhammad** [comment]
@sarahahmed i pulled c3_sarah_sprint0 , ur having a lot of failures in the budget controller and budget sources controller tests and the budget controller model and please write tests for views

**Comment by sarahahmed** [comment]
@yasmin-eltahan updated my umls , please review me

**Comment by sarahahmed** [comment]
@tokaabdelgabar , please review my documention and code

**Comment by yasmin-eltahan** [comment]
@sarahahmed  the arrows of the opt must be inside the box also the arrows cannot be going in several directions

**Comment by yasmin-eltahan** [comment]
@sarahahmed  this is for the edit and create

**Comment by yasmin-eltahan** [comment]
@sarahahmed  add the name of the actor please

**Comment by sarahahmed** [comment]
@yasmin-eltahan updated my UMLs please review me

**Comment by sarahahmed** [comment]
@tokaabdelgabar updated my documentation please review me

**Comment by yasmin-eltahan** [comment]
@sarahahmed senario verified

**Comment by nayera-muhammad** [comment]
tests verfied
