### ISSUE TITLE
As a project admin , i can connect a budget item to a task

### ISSUE THREAD

**Issue by sarahahmed** [yousraHazem/topsoft-13#143]
@yasmin-eltahan @nayera-muhammad 
@tokaabdelgabar

**Comment by yasmin-eltahan** [comment]
i verifed Uml

**Comment by yasmin-eltahan** [comment]
I verified senario

**Comment by sarahahmed** [comment]
@yasmin-eltahan please review

**Comment by yasmin-eltahan** [comment]
I verified this task

**Comment by yasmin-eltahan** [comment]
@sarahahmed  where is the UML ????

**Comment by sarahahmed** [comment]
@tokaabdelgabar updated documentation,please review me

**Comment by nayera-muhammad** [comment]
test verified
