### ISSUE TITLE
As a creator of a project I can delete a task on my project

### ISSUE THREAD

**Issue by salmaelruby** [yousraHazem/topsoft-13#144]
Success:
Through the task list page, the creator can click a button to delete a task, the he confirms the delete and clicks "ok".  The task should be deleted after confirmation
Tasks:
1. code
2. Documentation 
3. UML
4. tests
5. CSS & Bootstrap

**Comment by salmaelruby** [comment]
@yasmin-eltahan  please review my umls i corrected them :D  c2_salma_sprint1_umls

**Comment by salmaelruby** [comment]
@Riham-Gamal please review my code and scenario c2_salma_sprint1_delete_task

**Comment by salmaelruby** [comment]
@Donia1  please review my umls c2_salma_sprint1_umls

**Comment by Donia1** [comment]
@salma they all have the same problem write the name at the top then controllers under it

**Comment by salmaelruby** [comment]
@Riham-Gamal  please review my scenario and code c2_salma_sprint_1

**Comment by salmaelruby** [comment]
@Donia1  please review my scenario

**Comment by samaakram** [comment]
@salmaelruby 
code review:
fix the indentation problems in views and controllers

**Comment by samaakram** [comment]
@salmaelruby 
doc review:
it method does not return or arg anything then write that it doesnt args or return anything
 def create is without any doc

**Comment by salmaelruby** [comment]
@samaakram  i have corrected the code

**Comment by salmaelruby** [comment]
@samaakram  and doc

**Comment by samaakram** [comment]
@salmaelruby 
doc and code verified

**Comment by Donia1** [comment]
verified

**Comment by mariam-ismail** [comment]
The tests are not running, syntax error, unexpected end in line 143

**Comment by mariam-ismail** [comment]
verified your tests
