### ISSUE TITLE
As a creator of a project I can edit a task on my project

### ISSUE THREAD

**Issue by salmaelruby** [yousraHazem/topsoft-13#145]
Success:
by clicking on an edit button the creator is directed to another page where he can make the required changes and submit the new information.
@Riham-Gamal  @mariam-ismail  @Donia1 
Failure:
after editing the task description it was found that the task name already exists.

Tasks:
1. oode
2. Documentation 
3. UML 
4. test
5. Bootstrap

**Comment by salmaelruby** [comment]
@Donia1  please review my umls i corrected them :D  c2_salma_sprint1_umls

**Comment by salmaelruby** [comment]
@Riham-Gamal  please review my code and scenario

**Comment by Donia1** [comment]
@salmaelruby  change the name put at the top and controller at the bottom

**Comment by salmaelruby** [comment]
@Donia1  @samaakram  please review me

**Comment by salmaelruby** [comment]
@samaakram  please review me

**Comment by samaakram** [comment]
@salmaelruby 
doc and code verified

**Comment by Donia1** [comment]
verified

**Comment by mariam-ismail** [comment]
The tests are not running, syntax error, unexpected end in line 143

**Comment by mariam-ismail** [comment]
verified your tests
