### ISSUE TITLE
As a project creator I can assign tasks to a member on my project

### ISSUE THREAD

**Issue by salmaelruby** [yousraHazem/topsoft-13#146]
Success :
by clicking assign task : list of members appears then the creator choose member(s) and submit

@mariam-ismail   @Riham-Gamal @Donia1 

Tasks:
1. code
2. Documentation
3. UML 
4. test
5.  Bootstrap

**Comment by Donia1** [comment]
first you need to put a dotted line under the the stick figure and start from the top and do the time cycle part

**Comment by salmaelruby** [comment]
@Donia1   please review my umls i corrected them :D  c2_salma_sprint1_umls

**Comment by salmaelruby** [comment]
@Riham-Gamal  please review code and scenario

**Comment by salmaelruby** [comment]
@Riham-Gamal  please review my scenario and code c2_salma_sprint_1

**Comment by salmaelruby** [comment]
please review me @Donia1  @samaakram

**Comment by samaakram** [comment]
@salmaelruby 
doc and code verified

**Comment by Donia1** [comment]
verified

**Comment by mariam-ismail** [comment]
The tests are not running, syntax error, unexpected end in line 143

**Comment by mariam-ismail** [comment]
verified your tests
