### ISSUE TITLE
 As a project admin I can create/edit a budget item

### ISSUE THREAD

**Issue by yasmin-eltahan** [yousraHazem/topsoft-13#150]
success:
the user entering is a project admin,he will fill the budget item name, member associated with it, components of this budget item and click  finish

failures:
if the budget item is entered twice, an alert appears

Tasks:
1. code
2. Documentation
3. UML 
4. test
5. CSS & Bootstrap

@sarahahmed  @tokaabdelgabar @salmaelruby  @Riham-Gamal

**Comment by yasmin-eltahan** [comment]
@salmaelruby  please review my UML

**Comment by yasmin-eltahan** [comment]
@sarahahmed  please review my tests

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar please review code and documentation

**Comment by sarahahmed** [comment]
tests are correct

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  please review my senario
