### ISSUE TITLE
As an admin of a project I can create/edit the raised money for a budget of a project 

### ISSUE THREAD

**Issue by yasmin-eltahan** [yousraHazem/topsoft-13#151]
success:

the username entered is a project member , specify raised money and click save

failure:
enter an invalid number alert appears
enter a raised budget for a project that doesn't exist alert appears

Tasks:
1. code
2. Documentation
3. UML 
4. test
5. CSS & Bootstrap

@sarahahmed  @tokaabdelgabar  @Riham-Gamal  @salmaelruby

**Comment by salmaelruby** [comment]
@yasmin-eltahan  same simple mistake and add the white processing box and write the name of the actor such as (project admin , a member in a project..etc)

**Comment by salmaelruby** [comment]
@yasmin-eltahan  
UML reviewing , it needs in the edit to return the new attributes

**Comment by yasmin-eltahan** [comment]
@sarahahmed  please review my tests

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  can you please review my code

**Comment by sarahahmed** [comment]
@yasmin-eltahan , model test is missing

**Comment by yasmin-eltahan** [comment]
@sarahahmed  i added my model test please review

**Comment by sarahahmed** [comment]
tests are correct

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  please review my documentation and code

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  please review my senario

**Comment by tokaabdelgabar** [comment]
code and documentation verified

**Comment by yasmin-eltahan** [comment]
@salmaelruby  please review my UML

**Comment by salmaelruby** [comment]
reviewed ur umls :D
