### ISSUE TITLE
As a member associated with budget item  I can add attachments of receipts 

### ISSUE THREAD

**Issue by yasmin-eltahan** [yousraHazem/topsoft-13#152]
success:
The receipt is scanned and entered in the system

Tasks:
1. code
2. Documentation
3. UML 
4. test
5. CSS & Bootstrap

@sarahahmed  @salmaelruby @tokaabdelgabar @Riham-Gamal

**Comment by salmaelruby** [comment]
@yasmin-eltahan  i checked the uml for this story  they are correct except for that u should add a dotted line under the actor and it should have a vertical perpendicular line coming out of it . 
and the two lines coming from the opt should join back touching this vertical line

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  please review my scenario

@tokaabdelgabar  please review my code and documentation

**Comment by tokaabdelgabar** [comment]
documentation and code verified

**Comment by yasmin-eltahan** [comment]
@salmaelruby  please review my UML

**Comment by salmaelruby** [comment]
i checked the umls and there are common small things to be corrected ( i will write here but they are for all of them ) : 
- UI should be replaced by << view>>
  -the opt box is on only the required specific part 
- << view >> << controller>> .. etc should be up and the name of controller should be below it 
  -the arrow coming out of the admin should be touching the perpendicular line of the admin 
  -the returning arrow should return to the previous one at a time with a white box indicating time process
  
  i hope u understood my comments thank uu :D !

**Comment by yasmin-eltahan** [comment]
@salmaelruby  I updated the UML please review

**Comment by salmaelruby** [comment]
reviewed ur umls :D
