### ISSUE TITLE
As a user of the project I can view My projects list

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#154]
@yasmin-eltahan @sarahahmed @Riham-Gamal @salmaelruby

**Comment by tokaabdelgabar** [comment]
@sarahahmed please review my tests (they run)
@yasmin-eltahan please review my UMLs and the user senario
@Riham-Gamal please review my code
@salmaelruby please review my documentation

**Comment by sarahahmed** [comment]
modify  variable names

**Comment by salmaelruby** [comment]
viewed the documentation its correct :D

**Comment by sarahahmed** [comment]
test is correct

**Comment by tokaabdelgabar** [comment]
@sarahahmed please review my tests (they run)
@yasmin-eltahan please review the  senario
@Riham-Gamal please review my code
@salmaelruby please review my documentation

**Comment by yasmin-eltahan** [comment]
Please remove twitter bootstrap

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  I have removed the twitter bootstrap

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  remove the yellow color of the table

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  check senario and uml

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar senario verified 

for the UML same problem

**Comment by yasmin-eltahan** [comment]
UML verified
