### ISSUE TITLE
as a user i can sign up in MME7

### ISSUE THREAD

**Issue by Donia1** [yousraHazem/topsoft-13#155]
success: 
add all the information needed to create an account, the username is unique and password encrypted and all the information need is in (first name, last name, email, phone number, username, password, address 
failure:
forgot to add a detail, already a member, username already exists 
TASKS:
rspec test 
the view 
encryption gem for the password 
documentation of methods
story sequence diagram

@samaakram @mayBadr @mariam-ismail @yasmin-eltahan

**Comment by yasmin-eltahan** [comment]
I have checked the UML and verified it

**Comment by samaakram** [comment]
@Donia1 
Doc Review:
in admin controller, wrong documentation/description of def new, this method does not redirect to any other page as stated and also doesnt take any params
in app controller change the descriptions to something like it takes first id and finds it in users to be more clear

**Comment by samaakram** [comment]
@Donia1 
Code Review:
in user controller: wrong indentation with def show. so u should unindent def show line
in admin helper, session helper, user helper: indentation problems with def's ends. make sure they have same indentation as their opening defs
in views/admin/index.html.erb: indentation problem. line 9, 24, 26 should have same indentation
and you have to closing divs without their opening so should be removed from line 16 and 17

**Comment by mayBadr** [comment]
@Donia1 
scenario review:
1. ur Arabic sux...correct it!!
2. remove time stamp
3. as an admin....add a logout link!!
4. in signUp page ....error msg is in english and arabic!! 
   5.name not allowed to be  number !!

**Comment by mayBadr** [comment]
checked scenario!! verified!

**Comment by mariam-ismail** [comment]
session controller rspec rename description of logout and create lines 33 and 20

**Comment by mariam-ismail** [comment]
bundle exec rspec spec/ is not running

**Comment by mariam-ismail** [comment]
uninitialized constant CarrierWave when running the test please check it out

**Comment by mariam-ismail** [comment]
you have 0 failures but you have pending examples

**Comment by Donia1** [comment]
@yasmin-eltahan i have redid my uml for signup

**Comment by yasmin-eltahan** [comment]
you can't go directly from the button to the model

**Comment by Donia1** [comment]
@samaakram please check my documentation

**Comment by Donia1** [comment]
@yasmin-eltahan check my uml please

**Comment by Donia1** [comment]
@samaakram in here is my latest version

**Comment by samaakram** [comment]
Code Review:
in ApplicationController & UsersController & UsersHelper & app / views / admin / show.html.erb & app / views / user/_getMyGroups.html.erb , show.html.erb
wrong indentation

**Comment by samaakram** [comment]
@Donia1 
documentation review:
in SessionsController:
you can delete the def new since you dint use it and put the documentation just for def create and def destroy you misspelled returns
in UsersController:
def show wrong doc; it actually takes/ARGS the user.id and returns the groupUser record, where its user.id = current_user.id
def create it returns the new user record/session record so instead of saying all info about ... say record
in SessionsHelper
def log_in(user): either return user or user.id and take another look at the misspelled words 
and fill in the documentation for the rest of you methods
and while fixing the mistakes make sure you also wrote the ARGS/it takes statement

**Comment by Donia1** [comment]
@samaakram I cant take out def new because it creates the pages new in the views

**Comment by Donia1** [comment]
@samaakram  fix what u wrote here

**Comment by samaakram** [comment]
@Donia1 code verified
@Donia1 doc verified

**Comment by yasmin-eltahan** [comment]
@Donia1  UML verified
