### ISSUE TITLE
As a guest I can view groups

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#158]
Success: Click on "groups" button, view list with all group links, go to the group page
Failure: The page won't open. 
@Donia1  @samaakram  @mariam-ismail  @yasmin-eltahan 

Task:
1. Documentation @samaakram 
2. UML @Donia1 
3. CSS & Bootstrap

**Comment by mayBadr** [comment]
@Donia1  plz verify uml

**Comment by Donia1** [comment]
verified
