### ISSUE TITLE
As a guest I can view communities

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#162]
Success: Click on "community" button, view list with all communities links, go to the community page
Failure: The page won't open.  
@Donia1 @nayera-muhammad  @yasmin-eltahan 

Task:
1. Documentation @Donia1 
2. UML @Donia1 
3. CSS & Bootstrap

**Comment by mayBadr** [comment]
plz verify uml

**Comment by mayBadr** [comment]
@Donia1  plz verify uml

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@nayera-muhammad  can u plz verify my tests c1_may_allCommunities_spTwo...community controller!

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify the scenario c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@nayera-muhammad plz verify my tests.... c1_may_allCommunities_spTwo ....community controller

**Comment by nayera-muhammad** [comment]
you have got an unfinished test while testing the list

**Comment by mayBadr** [comment]
@nayera-muhammad i did the test...plz verify c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@Donia1  plz verify docs c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@yasmin-eltahan  plz verify scenario c1_may_allCommunities_spTwo

**Comment by Donia1** [comment]
verified

**Comment by nayera-muhammad** [comment]
tests verified

**Comment by yasmin-eltahan** [comment]
@mayBadr  I verified the senario
