### ISSUE TITLE
As an admin I can delete a community 

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#164]
@Donia1   @nayera-muhammad  @yasmin-eltahan 
Success: press on delete button, get an alert "are you sure you want to delete" and choose yes or no, if yes redirect to the same page after deleting, if no redirects to the same page without deleting
Failure: redirect to the same page without deleting the community 

Task:
1. Documentation @Donia1 
2. UML @Donia1 
3. CSS & Bootstrap

**Comment by yasmin-eltahan** [comment]
i verified this senario

**Comment by mayBadr** [comment]
@Donia1  plz verify uml

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@nayera-muhammad  can u plz verify my tests c1_may_allCommunities_spTwo...community controller!

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify the scenario c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@nayera-muhammad can u plz verify my tests c1_may_allCommunities_spTwo...community controller!

**Comment by nayera-muhammad** [comment]
please test the "rescue ActiveRecord::RecordNotFound"

**Comment by mayBadr** [comment]
@nayera-muhammad i did the test...plz verify c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@Donia1 plz verify docs c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify the scenario c1_may_allCommunities_spTwo

**Comment by nayera-muhammad** [comment]
tests verified

**Comment by Donia1** [comment]
verified

**Comment by yasmin-eltahan** [comment]
@mayBadr  I verified this senario
