### ISSUE TITLE
As a member I can edit a group

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#165]
@Donia1 
Success: press edit button, redirect to editing page, the member edits his work only and after finishing editing member gets an alert "are you sure of your changes" if yes redirect to the same page after editing, if no redirect to editing page again to correct or press go back link to go back to the groups page
Failure: edited something that the member didn't create, not his/her 

Tasks: 
1. Documentation @Donia1 
2. UML @Donia1 
3. Implementing the function logic 
4. CSS & Bootstrap

**Comment by yasmin-eltahan** [comment]
i verified this senario

**Comment by mayBadr** [comment]
@Donia1 plz verify uml

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@nayera-muhammad  plz verify my tests c1_may_allGroups_spTwo....groups_controller...edit and update methods

**Comment by mayBadr** [comment]
@Donia1 plz verify my doc c1_may_allGroups_spTwo.

**Comment by mayBadr** [comment]
@yasmin-eltahan  plz verify my scenario c1_may_allGroups_spTwo

**Comment by Donia1** [comment]
@mayBadr you have to put Author before your name

**Comment by mayBadr** [comment]
@Donia1  corrected my docs plz verify

**Comment by Donia1** [comment]
verified

**Comment by nayera-muhammad** [comment]
you are having 3 failures in the groups controller

**Comment by nayera-muhammad** [comment]
the edit part is verified

**Comment by mayBadr** [comment]
@nayera-muhammad ....these r not my tests...my tests r edit and update only!! cut the other test and run !

**Comment by mayBadr** [comment]
@Donia1 what's wrong with the doc label...why still reopen?

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify scenario c1_may_allGroups_spTwo

**Comment by Donia1** [comment]
verify
