### ISSUE TITLE
As a group creator I can add members in a group

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#166]
@Donia1 @samaakram @mariam-ismail @yasmin-eltahan 
Success: first get the list of member who aren't in the current group ,then start choosing and adding members  from the list, and when you press on the Add button records will be created for them in the tables and let them have access to this group
Failure: adding a member to the group who already exists in the group (duplicates)

Tasks: 
1. Documentation @Donia1 
2. UML @Donia1 
3. Implementing the function logic 
4. CSS & Bootstrap

**Comment by yasmin-eltahan** [comment]
i verified this senario

**Comment by mayBadr** [comment]
@Donia1 plz verify my doc c1_may_allGroups_spTwo.

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify my scenario c1_may_allGroups_spTwo

**Comment by Donia1** [comment]
@mayBadr you have to put Author before your name in group controller user controller group.rb

**Comment by mayBadr** [comment]
@Donia1 corrected my docs plz verify

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify scenario c1_may_allGroups_spTwo
