### ISSUE TITLE
As a creator of a post I can delete it

### ISSUE THREAD

**Issue by mariam-ismail** [yousraHazem/topsoft-13#173]
Success:
he deleted  his work only, redirect it to the same page after deleting, after you finish deleting you get an alert are you sure of your changes
Failure:
deleted something that he didn't create, 

Tasks:
1. Research on validations
2. Documentation
4. Implementing the function logic
5. Handling input errors
6. CSS & Bootstrap

@samaakram @mayBadr @Donia1

**Comment by mayBadr** [comment]
ok!!

**Comment by mariam-ismail** [comment]
@Riham-Gamal  please review the scenario

**Comment by mariam-ismail** [comment]
@salmaelruby  please review my UMLS in this branch c2_mariam_UMLS

**Comment by mariam-ismail** [comment]
@samaakram please  review me

**Comment by salmaelruby** [comment]
@mariam-ismail i have checked you umls they have common mistakes so please check my comment in the issue of ----175 As a member I can join a group

**Comment by mariam-ismail** [comment]
@sarahahmed please review my tests in post_controller_spec.rb

**Comment by sarahahmed** [comment]
@mariam-ismail tests verified

**Comment by Riham-Gamal** [comment]
scenario verified

**Comment by samaakram** [comment]
@mariam-ismail code and doc verified

**Comment by mariam-ismail** [comment]
@salmaelruby  please review my UMLS c2_mariam_UMLS

**Comment by salmaelruby** [comment]
@mariam-ismail  umls verified
