### ISSUE TITLE
As a member of the group I can create post

### ISSUE THREAD

**Issue by mariam-ismail** [yousraHazem/topsoft-13#174]
success:
a post is successfully created
failure:
he's not member in either the project or the group therefore he can't create a post

Tasks:
1. Research on validations
2. Documentation
4. Implementing the function logic
5. Handling input errors
6. CSS & Bootstrap
@samaakram @Donia1 @mayBadr

**Comment by mayBadr** [comment]
ok!

**Comment by mariam-ismail** [comment]
@Riham-Gamal  please review the scenario

**Comment by mariam-ismail** [comment]
@salmaelruby  please review my UMLS in this branch c2_mariam_UMLS

**Comment by mariam-ismail** [comment]
@samaakram please  review me

**Comment by salmaelruby** [comment]
@mariam-ismail  i have checked you umls they have common mistakes so please check my comment in the issue of  #175 As a member I can join a group

**Comment by mariam-ismail** [comment]
@sarahahmed please review my tests in post_controller_spec.rb

**Comment by sarahahmed** [comment]
@mariam-ismail tests verified

**Comment by samaakram** [comment]
@mariam-ismail code and doc verified :dancer: :dancer: :dancer:

**Comment by mariam-ismail** [comment]
@salmaelruby please review my umls c2_mariam_UMLS

**Comment by salmaelruby** [comment]
@mariam-ismail  verified umls
