### ISSUE TITLE
As a member I can join a group

### ISSUE THREAD

**Issue by mariam-ismail** [yousraHazem/topsoft-13#175]
Success:
a button is there  when you press on it we will add a record for him in the table and give access to the group
Failure:
we have to check if he is logged in and if not we redirect him to the signed up page 

Tasks:
1. Research on validations
2. Documentation
4. Implementing the function logic
5. Handling input errors
6. CSS & Bootstrap
@samaakram  @salmaelruby @Riham-Gamal @sarahahmed

**Comment by mayBadr** [comment]
ok

**Comment by mariam-ismail** [comment]
@samaakram please review my code and documentation

**Comment by samaakram** [comment]
@mariam-ismail 
code review
GroupUsersController line 13: indentation problem
rest is perfect

**Comment by mariam-ismail** [comment]
@Riham-Gamal please review me

**Comment by mariam-ismail** [comment]
@salmaelruby please review my UMLS

**Comment by mariam-ismail** [comment]
@samaakram please recheck my documentation

**Comment by samaakram** [comment]
@mariam-ismail 
code verified
doc verified

**Comment by mariam-ismail** [comment]
@sarahahmed please verify my tests

**Comment by Riham-Gamal** [comment]
the flash notice that appears after the member joins is not realistic

**Comment by mariam-ismail** [comment]
removed the flash notice @Riham-Gamal

**Comment by sarahahmed** [comment]
tests are correct

**Comment by mariam-ismail** [comment]
@salmaelruby  please review my UMLS in this branch c2_mariam_UMLS

**Comment by salmaelruby** [comment]
@mariam-ismail  i have reviewed your uml and here are my recommendations : 
- the admin actor is not put in box its just a line under the person like the letter " T "
- the view , models , controller should be written on a separate line meaning << view >> , << controller  >> , << Model >> then under each one is their name
  -please take care than the arrows are coming out the end of the white box  and it is heading to pint to the begininning of next white box 
- if there any params sent through the controllers and models please specify them . (group_id , user_id..etc ) 
- if there any params returning also please specify them 
  thank uu :D

**Comment by mariam-ismail** [comment]
@salmaelruby please review my umls c2_mariam_UMLS

**Comment by salmaelruby** [comment]
@mariam-ismail  verified umls
