### ISSUE TITLE
As a creator of a project I can view tasks of a project 

### ISSUE THREAD

**Issue by nayera-muhammad** [yousraHazem/topsoft-13#178]
branch name : c2_nayera_as_a_creator_view_project_tasks
product backlog number:  35
success:
view a list of the tasks available for a certain project
failure:
no task selected

 Tasks:
1. code @Riham-Gamal  
2. Documentation @salmaelruby 
3. UML @salmaelruby 
4. test @mariam-ismail 
5. Bootstrap

**Comment by nayera-muhammad** [comment]
@salmaelruby please review me and i added my uml files

**Comment by nayera-muhammad** [comment]
@salmaelruby  please review my documentation

**Comment by salmaelruby** [comment]
uml and doc verified
