### ISSUE TITLE
As a project creator I can edit project

### ISSUE THREAD

**Issue by nayera-muhammad** [yousraHazem/topsoft-13#179]
branch name: c2_nayera_as_a_creator_edit_project
product backlog number:  40
success:
I can edit project name, date and description
failure:
see if the dates and the name are valid after their modification

Tasks:
1. code  @Riham-Gamal
2. Documentation @salmaelruby 
3. UML @salmaelruby 
4. test @mariam-ismail 
5. Bootstrap

**Comment by nayera-muhammad** [comment]
@salmaelruby please review me and i added my uml files

**Comment by salmaelruby** [comment]
@nayera-muhammad  i have reviewed your umls just small correction should be made ..:
-- the << view >> , << controller >> .. etc should be up and name of controller/view below it 
-- the returning line should return to the previous one at a time .. meaning you return from the project model to the newProject view first then a white box indicating processing time , then an arrow from newProject view to Project controller and white box .. etc

**Comment by Riham-Gamal** [comment]
code and scenario are verified

**Comment by nayera-muhammad** [comment]
:*

**Comment by nayera-muhammad** [comment]
@salmaelruby  please review my documentation

**Comment by salmaelruby** [comment]
uml verified
