### ISSUE TITLE
As a User I can view all budget items

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#184]
@yasmin-eltahan @sarahahmed @Riham-Gamal @salmaelruby

**Comment by yasmin-eltahan** [comment]
add a dashed line from the actor and specify who is this actor

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  please review my senario 

@Riham-Gamal please review my code

**Comment by yasmin-eltahan** [comment]
please remove twitter bootstrap and all its associated files as we have agreed before that it raised a lot of errors

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  I removed twitter bootstrap

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar there is an edit button although he is not a creator please add the name of the project on top of the page to be more user friendly and remove the yellow color of the table there is also lot of empty fields in the table

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  check uml and senario

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar for the UML the arrow going to the view must be a little bit down 

for the senario please add the condition to check if he his the creator

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan can you check the senario

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  please fix the bootstrap issue

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  UML verified

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar i verified senario
