### ISSUE TITLE
tests for isCommentCreator and getProjectMembers

### ISSUE THREAD

**Issue by nayera-muhammad** [yousraHazem/topsoft-13#189]
@Riham-Gamal   @salmaelruby @mariam-ismail 
branch name: c2_nayera_comment_projectuser_tests

Tasks:
1. code @Riham-Gamal 
2. Documentation @salmaelruby 
3. UML  @salmaelruby 
4. test @mariam-ismail

**Comment by salmaelruby** [comment]
UML review : add the user in the same level and dotted line under it 
 add the models and the UI 
return the output

**Comment by nayera-muhammad** [comment]
@Riham-Gamal  please review my code in comment.rb and project_user.rb this branch is only for testing

**Comment by nayera-muhammad** [comment]
@salmaelruby  please review my documentation

**Comment by nayera-muhammad** [comment]
@salmaelruby please review me and i added my uml files

**Comment by salmaelruby** [comment]
um verified
