### ISSUE TITLE
As a creator of a project I can create a task on my project

### ISSUE THREAD

**Issue by salmaelruby** [yousraHazem/topsoft-13#200]
Success :
the admin is redirected to a page where he adds the description of the new task 

Failure: 
a message appears if the description of the task already exits 
a message appears if he clicks submit without inserting the description

Tasks:
1. code
2. Documentation
3. UML 
4. test
5. Bootstrap

**Comment by Donia1** [comment]
same as before the dotted line user the user

**Comment by nayera-muhammad** [comment]
@salmaelruby if u have added the tests please notify me and mention the branch name in oreder to review u

**Comment by nayera-muhammad** [comment]
@salmaelruby  please reconsider ur tests and remove other stuff in order to remove errors in other files

**Comment by nayera-muhammad** [comment]
@salmaelruby they are not fully changed please check them again

**Comment by salmaelruby** [comment]
@Donia1  please review my umls i corrected them :D  c2_salma_sprint1_umls

**Comment by salmaelruby** [comment]
@nayera-muhammad  i corrected the tests please review me c2_salma_sprint1_delete_task

**Comment by salmaelruby** [comment]
@Riham-Gamal  please review my code and scenario c2_salma_sprint1_delete_task

**Comment by Donia1** [comment]
@salmaelruby put the name up and the <<controller>> /<<view>> down under the name

**Comment by salmaelruby** [comment]
@Riham-Gamal  please review my code and scenario c2_salma_sprint_1

**Comment by Riham-Gamal** [comment]
@salmaelruby 
please change the Milestone ti sprint 2 
the text in the table should be right aligned not left 
the delete button and ta3yeen a3da2 are to close to each other
make the text box of the task description larger

**Comment by salmaelruby** [comment]
please review me @Donia1 @samaakram

**Comment by samaakram** [comment]
@salmaelruby 
doc and code verified

**Comment by mariam-ismail** [comment]
The tests are not running, syntax error, unexpected end in line 143

**Comment by mariam-ismail** [comment]
verified your tests

**Comment by Donia1** [comment]
verified umls :D
