### ISSUE TITLE
As an admin I can add and remove members from the project

### ISSUE THREAD

**Issue by Riham-Gamal** [yousraHazem/topsoft-13#202]
@salmaelruby @nayera-muhammad  @mayBadr  @samaakram 

Success :
members are added successfully 
the admin is redirected to a project page where he finishes creating the project

Failure: 
members are not  added successfully 
the admin is not redirected to the project page

Tasks:
1. code
2. Documentation
3. UML 
4. test
5. Bootstrap

**Comment by nayera-muhammad** [comment]
@Riham-Gamal if u have added the tests please notify me and mention the branch name in oreder to review u

**Comment by samaakram** [comment]
@Riham-Gamal can you tell me what should i review? code or documentation?? and add a comment with your branch name

**Comment by salmaelruby** [comment]
@Riham-Gamal  already no umls for this story to be done :D

**Comment by salmaelruby** [comment]
doc verified :D

**Comment by Riham-Gamal** [comment]
@mayBadr please review the scenario

**Comment by Riham-Gamal** [comment]
@yasmin-eltahan please review the scenario

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  I verified the code and senario

**Comment by salmaelruby** [comment]
doc verified
