### ISSUE TITLE
As a user I can view my project page 

### ISSUE THREAD

**Issue by Riham-Gamal** [yousraHazem/topsoft-13#203]
@salmaelruby @mayBadr @samaakram  @nayera-muhammad 

Success :
the user view his project page

Tasks:
1. code
2. Documentation
3. UML 
4. test
5. Bootstrap

**Comment by salmaelruby** [comment]
i have viewed the documentation

**Comment by mayBadr** [comment]
scenario Ok!

**Comment by nayera-muhammad** [comment]
please ask if this story will be reopened or not because its already merged

**Comment by nayera-muhammad** [comment]
@Riham-Gamal i couldnt find ur tests on master please specify me the files

**Comment by Riham-Gamal** [comment]
@salmaelruby  I added the umls in branch c2_Riahm_umls_sprint1

**Comment by salmaelruby** [comment]
@Riham-Gamal  i have seen the umls i have just 2 comments : please raise the user (u dnt have to draw him manually u will find a drawing of the stick man in the uml section in cacoo) and he should be up at the same level of boxes of the views and models , secondly there is a white  box missing between return project of the controller and the view

**Comment by salmaelruby** [comment]
reviewed ur umls :D

**Comment by nayera-muhammad** [comment]
tests verified

**Comment by samaakram** [comment]
Code verified

**Comment by samaakram** [comment]
@Riham-Gamal  dont forget to re-choose the assign to and change the milestone to sprint 2

**Comment by Riham-Gamal** [comment]
ok @samaakram

**Comment by salmaelruby** [comment]
doc verified ;)

**Comment by Riham-Gamal** [comment]
@mayBadr please review the scenario

**Comment by mayBadr** [comment]
scenario checked!
