### ISSUE TITLE
as a guest i can view budget sources

### ISSUE THREAD

**Issue by sarahahmed** [yousraHazem/topsoft-13#204]
@tokaabdelgabar 
@yasmin-eltahan 
@nayera-muhammad

**Comment by yasmin-eltahan** [comment]
I verified the UML

**Comment by yasmin-eltahan** [comment]
I verified the senario

**Comment by nayera-muhammad** [comment]
@sarahahmed  have u included the tests for this story? , if yes please let me know

**Comment by sarahahmed** [comment]
@nayera-muhammad  yes i did [branch c3_sarah_sprint0]

**Comment by sarahahmed** [comment]
@tokaabdelgabar  i update my documentation and code , please review me

**Comment by tokaabdelgabar** [comment]
@sarahahmed  what is the name of the branch

**Comment by yasmin-eltahan** [comment]
UML verified

**Comment by tokaabdelgabar** [comment]
@sarahahmed you have to mention 
#Inputs: ????? and Outputs: ??????
#Returs: Array of Budget Items 
for the documentation

**Comment by sarahahmed** [comment]
@tokaabdelgabar  i updated my documentation, please review me

**Comment by nayera-muhammad** [comment]
verified ur tests

**Comment by yasmin-eltahan** [comment]
@sarahahmed senario verified
