### ISSUE TITLE
Gems and tables 

### ISSUE THREAD

**Issue by yasmin-eltahan** [yousraHazem/topsoft-13#223]
@sarahahmed @samaakram @Donia1 @mayBadr @salmaelruby @mariam-ismail @Riham-Gamal @tokaabdelgabar @nayera-muhammad

**Comment by Donia1** [comment]
could u please add 
gem "bcrypt-ruby", :require => "bcrypt"
gem 'simplecov'
 gem 'annotate', '2.5.0'
 gem 'factory_girl_rails', '4.1.0'

**Comment by mariam-ismail** [comment]
@yasmin-eltahan could you please add group :test do
  gem 'faker'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
end

**Comment by Donia1** [comment]
can u please add 
gem 'omniauth-facebook'

**Comment by nayera-muhammad** [comment]
install this please 
gem 'bootstrap-datepicker-rails'
