### ISSUE TITLE
as a member i can sign in with my facebook account 

### ISSUE THREAD

**Issue by Donia1** [yousraHazem/topsoft-13#226]
success:
successful connection to FB server, redirection to the page
Failure: 
he entered the email/password wrong or FB is not connected to our system
Tasks: 
go to facebook develpor and create an app on it for the website 
code and docmentation
sequence diagram
rspec
omniauth-facebook
Facebook Client-Side Authentication
Facebook Server-Side Authentication
@mayBadr @yasmin-eltahan @mariam-ismail @samaakram

**Comment by Donia1** [comment]
@yasmin-eltahan can u please check my uml

**Comment by Donia1** [comment]
@yasmin-eltahan @mayBadr can you guys please check my work thank u :D

**Comment by yasmin-eltahan** [comment]
@Donia1  I verified senario
