### ISSUE TITLE
As a member of a project I can associate hash tag on twitter/ share on facebook

### ISSUE THREAD

**Issue by mariam-ismail** [yousraHazem/topsoft-13#238]
Success: 1.add link to the #tags, post/view a tweet associated with this tag/ 2.add a link, add "share on FB"
Failure: 1.already exists, no #tags associated with the project/ 2.not creator, not owner (not admin) of the page, 

Tasks:
1. Research on validations
2. Documentation
4. Implementing the function logic
5. Handling input errors
6. CSS & Bootstrap
@samaakram @sarahahmed @salmaelruby @Riham-Gamal

**Comment by mariam-ismail** [comment]
@Riham-Gamal please review the scenario

**Comment by mariam-ismail** [comment]
@samaakram please review my code and documentation in projects show

**Comment by Riham-Gamal** [comment]
@mariam-ismail 
scenario verfied

**Comment by mariam-ismail** [comment]
@samaakram please review

**Comment by samaakram** [comment]
@mariam-ismail doc & code verified

**Comment by mariam-ismail** [comment]
@salmaelruby please review my UMLS

**Comment by salmaelruby** [comment]
@mariam-ismail  umls verified
