### ISSUE TITLE
As a guest/user I can search groups

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#240]
@Donia1 @samaakram @mariam-ismail @yasmin-eltahan 

Success: type a group name, get the link of this group 
Failure: The group name the guest typed cannot be found

Task:
1. Documentation @Donia1 
2. UML @Donia1 
3. CSS & Bootstrap

**Comment by mayBadr** [comment]
@Donia1 verify uml

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@samaakram  plz verify my doc c_may_allGroups_spTwo

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify my scenario c1_may_allGroups_spTwo

**Comment by samaakram** [comment]
@mayBadr im not in your component anymore so im not your reviewer

**Comment by mayBadr** [comment]
@nayera-muhammad plz verify my tests c1_may_allGroups_spTwo....groups_controller...edit and update methods

**Comment by mayBadr** [comment]
@Donia1 plz verify my doc c1_may_allGroups_spTwo.

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify my scenario c1_may_allGroups_spTwo

**Comment by Donia1** [comment]
@mayBadr you have to put Author before your name in group controller user controller group.rb

**Comment by mayBadr** [comment]
@Donia1  corrected my docs plz verify

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@nayera-muhammad  did the test....plz verify c1_may_allGroups_spTwo

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify scenario c1_may_allGroups_spTwo

**Comment by nayera-muhammad** [comment]
there is a failure in line 14 in group_spec.rb

**Comment by mayBadr** [comment]
it's not my test...my test is ....it "should respond to (search)" do....only

**Comment by nayera-muhammad** [comment]
tests verified

**Comment by Riham-Gamal** [comment]
scenario verified

**Comment by Donia1** [comment]
code verified
