### ISSUE TITLE
As a guest/user I can search communities

### ISSUE THREAD

**Issue by mayBadr** [yousraHazem/topsoft-13#241]
@Donia1  @nayera-muhammad l @yasmin-eltahan 

Success: type a community name, get the link of this community 
Failure: The community the guest/user typed cannot be found

Task:
1. Documentation @Donia1 
2. UML @Donia1 
3. CSS & Bootstrap

**Comment by mayBadr** [comment]
@Donia1  plz verify UML

**Comment by Donia1** [comment]
verified

**Comment by mayBadr** [comment]
@nayera-muhammad  .... can u plz verify my tests c1_may_allCommunities_spTwo...community controller!

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify the scenario c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@nayera-muhammad can u plz verify my tests c1_may_allCommunities_spTwo...community controller!

**Comment by nayera-muhammad** [comment]
please do tests for you search in the model

**Comment by mayBadr** [comment]
@nayera-muhammad  i did the tests...plz verify c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@Donia1 plz verify the doc c1_may_allCommunities_spTwo

**Comment by mayBadr** [comment]
@yasmin-eltahan plz verify the scenario c1_may_allCommunities_spTwo

**Comment by nayera-muhammad** [comment]
tests verified

**Comment by Donia1** [comment]
verified

**Comment by yasmin-eltahan** [comment]
@mayBadr  I verified the senario

**Comment by Donia1** [comment]
verified
