### ISSUE TITLE
as a creator i can delete a project

### ISSUE THREAD

**Issue by nayera-muhammad** [yousraHazem/topsoft-13#257]
branch name: c2_nayera_as_a_creator_delete_project
product backlog number: 44
success:
deleted successfuly and its budgets
failure:
can't be deleted if it has budgets

Tasks:
1. code @Riham-Gamal
2. Documentation @salmaelruby 
3. UML @salmaelruby 
4. test @mariam-ismail 
5. Bootstrap

**Comment by nayera-muhammad** [comment]
@Riham-Gamal  please review my scenario and and code , @salmaelruby  please review my documentation

**Comment by nayera-muhammad** [comment]
@salmaelruby  i have added the uml please review them they are on c2_nayera_as_a_creator_delete_project , theres a file called NayeraSprin2Umls inside it there is deleteProject.pdf ... thq  and please review the documentation as well

**Comment by nayera-muhammad** [comment]
@mariam-ismail  please review my tests

**Comment by mariam-ismail** [comment]
@nayera-muhammad  verified your tests

**Comment by salmaelruby** [comment]
@nayera-muhammad  i reviewed ur umls  and doc

**Comment by Riham-Gamal** [comment]
scenario and code verified
