### ISSUE TITLE
26- As a member I can add photos to a project / attachments

### ISSUE THREAD

**Issue by salmaelruby** [yousraHazem/topsoft-13#266]
Success  : 
browse then upload, add more photos/ videos / attachments / added successfully 

Failure : 
try again, not enough space, incorrect format/the user hasn't attached anything or wrong file

Tasks : 
-UML 
- tests
  -Scenario 
  -Code 
  -CSS

**Comment by salmaelruby** [comment]
@mariam-ismail please review my tests
@Riham-Gamal  please review my scenario c2_salma_sprint2_unassign
@samaakram  please review my code and doc

**Comment by samaakram** [comment]
@salmaelruby code and doc verified

**Comment by yasmin-eltahan** [comment]
@salmaelruby  Verified senario

**Comment by Donia1** [comment]
umls verified
