### ISSUE TITLE
as a project creator i can unassign tasks to members

### ISSUE THREAD

**Issue by salmaelruby** [yousraHazem/topsoft-13#268]
Success : 
only members in this project who are assigned appears and project creator unassigns a task to a member 

tasks : 
-UML
-code and documentation
-css
-tests

**Comment by salmaelruby** [comment]
@mariam-ismail please review my tests
@Riham-Gamal  please review my scenario c2_salma_sprint2_unassign
@samaakram  please review my code and doc

**Comment by samaakram** [comment]
@salmaelruby  doc and code verified

**Comment by yasmin-eltahan** [comment]
@salmaelruby  I verified senario

**Comment by salmaelruby** [comment]
@Donia1  please review my umls

**Comment by Donia1** [comment]
uml verified
