### ISSUE TITLE
As a project admin I can promote members

### ISSUE THREAD

**Issue by Riham-Gamal** [yousraHazem/topsoft-13#273]

**Comment by Riham-Gamal** [comment]
@yasmin-eltahan   please review the scenario c2_Riham_project_promote_members

**Comment by Riham-Gamal** [comment]
@salmaelruby  please review the documentation c2_Riham_project_promote_members

**Comment by Riham-Gamal** [comment]
@mariam-ismail  please review the tests c2_Riham_project_promote_members

**Comment by Riham-Gamal** [comment]
@samaakram  please review the code c2_Riham_project_promote_members

**Comment by mariam-ismail** [comment]
@Riham-Gamal  verified your tests

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  senario verified

**Comment by samaakram** [comment]
@Riham-Gamal code verified

**Comment by salmaelruby** [comment]
@Riham-Gamal  doc verified

**Comment by salmaelruby** [comment]
@Riham-Gamal  umls verified
