### ISSUE TITLE
as a member i should recieve notifications for any updates

### ISSUE THREAD

**Issue by sarahahmed** [yousraHazem/topsoft-13#282]
success: i should be able to receive notifications for any updates in my projects , or groups

Tasks:
1. code @tokaabdelgabar
2. Documentation @tokaabdelgabar 
3. UML  @yasmin-eltahan 
4. test  @nayera-muhammad 
5. CSS & Bootstrap

**Comment by sarahahmed** [comment]
@yasmin-eltahan  please review

**Comment by yasmin-eltahan** [comment]
@sarahahmed senario verified

**Comment by sarahahmed** [comment]
@tokaabdelgabar please review

**Comment by sarahahmed** [comment]
@nayera-muhammad  please review

**Comment by nayera-muhammad** [comment]
u have multiple migrations i couldn't test ur tests

**Comment by tokaabdelgabar** [comment]
@sarahahmed can you fix the code of budget items controller

**Comment by sarahahmed** [comment]
@tokaabdelgabar  this contoller belogs to yasmin

**Comment by nayera-muhammad** [comment]
tests verified
