### ISSUE TITLE
As a user I can add profile picture

### ISSUE THREAD

**Issue by Riham-Gamal** [yousraHazem/topsoft-13#283]
@samaakram @salmaelruby @mariam-ismail @yasmin-eltahan 
Success: 
I can add a pp and it appears on my profile 

Failure:
The pp does not appear on my profile

**Comment by Riham-Gamal** [comment]
@yasmin-eltahan please review the scenario c2_Riham_add_pp

**Comment by Riham-Gamal** [comment]
@salmaelruby please review the documentation  c2_Riham_add_pp

**Comment by Riham-Gamal** [comment]
@samaakram  please review the code c2_Riham_add_pp

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  I verified the senario

**Comment by salmaelruby** [comment]
@riham i have reviewed the doc

**Comment by samaakram** [comment]
@Riham-Gamal code verified

**Comment by salmaelruby** [comment]
@Riham-Gamal  umls verified
