### ISSUE TITLE
As a group creator I can promote group members

### ISSUE THREAD

**Issue by Riham-Gamal** [yousraHazem/topsoft-13#284]
@samaakram @salmaelruby @mariam-ismail @yasmin-eltahan 
Success:
The group member becomes a creator the button next to his name changes

Failure
The button stays the same

**Comment by Riham-Gamal** [comment]
@yasmin-eltahan please review the scenario c2_Riham_group_promote_members

**Comment by Riham-Gamal** [comment]
@mariam-ismail  please review the tests c2_Riham_group_promote_members

**Comment by Riham-Gamal** [comment]
@samaakram   please review the code c2_Riham_group_promote_members

**Comment by Riham-Gamal** [comment]
@salmaelruby  please review the documentation c2_Riham_group_promote_members

**Comment by mariam-ismail** [comment]
@Riham-Gamal  verified you tests

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  Senario verified

**Comment by salmaelruby** [comment]
@riham doc verfified

**Comment by samaakram** [comment]
@Riham-Gamal code verified

**Comment by salmaelruby** [comment]
@Riham-Gamal  reviewed umls
