### ISSUE TITLE
User Layout

### ISSUE THREAD

**Issue by yasmin-eltahan** [yousraHazem/topsoft-13#286]
@sarahahmed  @Riham-Gamal @tokaabdelgabar @salmaelruby

**Comment by yasmin-eltahan** [comment]
@Riham-Gamal  please review my senario

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  please review my code

**Comment by Riham-Gamal** [comment]
@yasmin-eltahan 
the white color of the text is not clear
make the description of the carousel in the list right aligned 
after creating the carousel redirect to the show action not to the list 
change all the language to arabic

**Comment by Riham-Gamal** [comment]
@yasmin-eltahan
scenario verified

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  verified documentation
