### ISSUE TITLE
As an admin I can assign user to budget items

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#290]
@yasmin-eltahan @sarahahmed @samaakram  @salmaelruby 
Success: when assigning the user enters the user and budget item and gets assigned  
Failure: no failure

Task:
1. Documentation @salmaelruby  
2. UML @yasmin-eltahan 
3. CSS & Bootstrap

**Comment by tokaabdelgabar** [comment]
@Riham-Gamal please review my code 
@salmaelruby please review my documentation

**Comment by salmaelruby** [comment]
@tokaabdelgabar  i have reviewed the documentation

**Comment by tokaabdelgabar** [comment]
@samaakram please review my code

**Comment by tokaabdelgabar** [comment]
@samaakram please review code and documentation 
@yasmin-eltahan please review senario

**Comment by samaakram** [comment]
@tokaabdelgabar  doc and code verified

**Comment by tokaabdelgabar** [comment]
@sarahahmed  test of budget_item_users done please review

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar  , add params to the assign method

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  check senario again 
@sarahahmed  check test again

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar tests are correct

**Comment by tokaabdelgabar** [comment]
@Donia1 please verify uml

**Comment by Donia1** [comment]
@tokaabdelgabar verified
