### ISSUE TITLE
admin layout 

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#291]
As an admin I have a seperate layout from the user 
success :+ admin log in and see everything in his view
faliure: see the view of the user 

tasks:
add new layout 

@yasmin-eltahan @sarahahmed @Riham-Gamal @salmaelruby 
@Donia1 @mayBadr @mariam-ismail @nayera-muhammad @samaakram

**Comment by tokaabdelgabar** [comment]
guys any one who needs a button for the admin page tell me here so I can add it 
thank you

**Comment by tokaabdelgabar** [comment]
@Riham-Gamal please review code 
@yasmin-eltahan please review senario

**Comment by tokaabdelgabar** [comment]
@yasmin-eltahan  fixed senario :+1:

**Comment by yasmin-eltahan** [comment]
@tokaabdelgabar Senario verified

**Comment by tokaabdelgabar** [comment]
@samaakram  please verify code

**Comment by samaakram** [comment]
@tokaabdelgabar code verified
