### ISSUE TITLE
when the project ends it must be frozen on the website 

### ISSUE THREAD

**Issue by nayera-muhammad** [yousraHazem/topsoft-13#303]
branch name: c2_nayera_as_a_system_freeze_projects
product backlog number: 37
success:
project buttons frozen
failure:
project is still in process , 

Tasks:
1. code @Donia1 
3. UML @Donia1

**Comment by nayera-muhammad** [comment]
@mayBadr  please review my scenario

**Comment by nayera-muhammad** [comment]
@donia please review my code

**Comment by nayera-muhammad** [comment]
the file is app/views/projects/show.html.erb

**Comment by mayBadr** [comment]
@nayera-muhammad correct the button..it has to appear even if project frozen

**Comment by nayera-muhammad** [comment]
@donia please verify my umls in c2_nayera_as_a_creator_edit_project/NayeraSprint2Umls/freezeProjecUml.pdf

and verify my code in c2_nayera_a_frozen_projects in app/views/project/show.html

**Comment by Donia1** [comment]
@nayera-muhammad  in between show button and hide button there has a dotted line that will be written on it "else" thats all

**Comment by Donia1** [comment]
@nayera-muhammad verified

**Comment by nayera-muhammad** [comment]
@Donia1  i have adjusted the umls

**Comment by Donia1** [comment]
@nayera-muhammad verified

**Comment by nayera-muhammad** [comment]
@mayBadr please verify my scenario

**Comment by mayBadr** [comment]
scenario verified!
