### ISSUE TITLE
As a system I want to be able to get posts

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#70]
@yasmin-eltahan @sarahahmed @nayera-muhammad

**Comment by nayera-muhammad** [comment]
please reconsider the explanation for the method get_tasks

**Comment by nayera-muhammad** [comment]
sorry this is ok

**Comment by sarahahmed** [comment]
put the method in the helper
Helpers' dont take type of the input
remove "@" from the variable name

**Comment by yasmin-eltahan** [comment]
amed the UMl with the same concept of the other task

**Comment by nayera-muhammad** [comment]
u should add ( Author : Toka abdelgabar  22-.... ) before the explanation
