### ISSUE TITLE
as a system I should know who is not in this  project 

### ISSUE THREAD

**Issue by Donia1** [yousraHazem/topsoft-13#71]
donia's story 
@samaakram @mayBadr @mariam-ismail

**Comment by Donia1** [comment]
c1_donia_memberNotInProject

**Comment by Donia1** [comment]
@yasmin-eltahan

**Comment by yasmin-eltahan** [comment]
the result of the method is taken back to the helper not to another model

**Comment by yasmin-eltahan** [comment]
the model name is wrong it is project users not project
