### ISSUE TITLE
As a stystem I want to be able to get tasks of a project

### ISSUE THREAD

**Issue by tokaabdelgabar** [yousraHazem/topsoft-13#72]
@yasmin-eltahan @sarahahmed @nayera-muhammad

**Comment by nayera-muhammad** [comment]
please reconsider the explanation for the method get_tasks

**Comment by sarahahmed** [comment]
please put the method in the helper
 and check names of the Models

**Comment by yasmin-eltahan** [comment]
for the UML you can't have a controller without the view also your methods are supposed to be in the helper so it needs to be reflected on the UML

**Comment by nayera-muhammad** [comment]
u should add ( Author : Toka abdelgabar 22-.... ) before the explanation

**Comment by tokaabdelgabar** [comment]
@nayera-muhammad  please check the documentation
